version: '3.8'
services:

  api:
    build:
      context: .
    depends_on:
      database:
        condition: service_healthy
    restart: always
    deploy:
      replicas: 1
    ports:
      - "8000:8000"
    volumes:
      - .:/code/
    command: ["bash", "-c","dbmate up && gunicorn -c settings/gunicorn.conf.py app.main:app"]
    env_file:
      - .env
  ingest:
    build:
      context: .
    depends_on:
      - nats
    restart: always
    volumes:
      - .:/project/
    command: [ "bash", "-c", "python -m app.ingest" ]
    env_file:
      - .env

  qdrant:
    restart: always
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
  nats:
    image: nats
    restart: always
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"

  database:
    restart: always
    image: postgres:15-alpine
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U application" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: application
      POSTGRES_PASSWORD: secret_pass
      POSTGRES_DB: application
    ports:
      - "5432:5432"

volumes:
  pg-data:
    driver: local
